### ISSUE TITLE
Duplicated entries in search results

### ISSUE THREAD

**Issue by azurenekowo** [4pii4/piehtvn#8]
Steps to replicate:
- Search for queries that only has a few results
Ex. `/search?query=TS%20Revolution&pages=10`
- See the results (all are the same)
![image](https://github.com/4pii4/piehtvn/assets/67498765/69545bba-c739-4cc4-9170-bcd55a9bc145)

**Comment by azurenekowo** [comment]
Temporary resolved it in Charlotte.
```diff
# /routes/api/search.js
const express = require('express')
const router = express.Router()
+ const _ = require('lodash')
...
const data = await res.json()
- const doujinData = Object.values(data)[0]
+ const doujinData = _.uniqWith([...new Set(Object.values(data)[0].flat())], _.isEqual)
response.setHeader('Content-Type', 'application/json').send({ success: true, data: doujinData })
```

This will (hopefully) remove the duplicates. At the cost of another dependency for the API.
Sorting and paging will be done by the frontend later on.

**Comment by 4pii4** [comment]
I will change the search endpoint to accept a single page number and return the maximum pages of result for that query (along with the doujins within that page)

**Comment by 4pii4** [comment]
implemented single page search & page number limitations as of https://github.com/4pii4/piehtvn/commit/bca2f91b522a00167418e4579157984de67c92a8
